### PR TITLE
Development instructions

### PR DESCRIPTION
**Pull request by s0enke**

### CODE REVIEW

**Comment by s0enke** [comment]
@lassediercks please take a look

**Comment by lassediercks** [comment]
oh sweet, I'll have a look on friday

**Comment by s0enke** [comment]
merging as it is documentation and can be changed anytime

**Comment by lassediercks** [comment]
tbh. I'm failing on this step:

> Create a new Google Apps Script project. It will be the development and hosting environment for this app.

I digged through https://developers.google.com/apps-script/quickstart/docs

Or do does this just mean
`mkdir googleapsproject` ??

**Comment by s0enke** [comment]
> tbh. I'm failing on this step:
> 
> Create a new Google Apps Script project. It will be the development and hosting environment for this app.

Have a look at https://developers.google.com/apps-script/overview - you have to create a new Google Apps Script project, You can also do this via drive.google.com -> New -> More -> Google Apps Script.

HTH

**Pull request merged**
